### PR TITLE
Update link to rack-routing

### PR DESCRIPTION
**Pull request by georgeu2000**

### CODE REVIEW

**Comment by waghanza** [comment]
Thanks for update, but the change has to be made directly in the source code https://github.com/tbrand/which_is_the_fastest/blob/master/tools/src/benchmarker.cr#L51 (it will be overwritten otherwise)

**Comment by waghanza** [comment]
@georgeu2000 I can see that the link (leading to github) to the source code is dead, based on https://rubygems.org/gems/rack-routing

**Comment by georgeu2000** [comment]
Oh, that's right. I forgot that the change has to be made directly in the source code. Thank you for updating it.

I'll see if I can fix rubygems.

**Comment by georgeu2000** [comment]
OK, updated. Thanks for letting me know about rubygems link.

**Comment by georgeu2000** [comment]
How do I fix the conflict? Do I need a new branch and new PR?

**Pull request merged**
