### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by waghanza**

### CODE REVIEW

**Comment by tbrand** [comment]
AWESOME!! :+1:

**Comment by waghanza** [comment]
Just waiting for test suite to pass

**Comment by tbrand** [comment]
Great!
Will you add other templates like bug reports, feature request, question and so on?
Of course you don't have to include them in this PR anyway.

**Comment by waghanza** [comment]
sure, as it's a **new** feature for me (never used before), I'll test it before.

I thus planning to add some documentation, in order to increase the community / tools used

**Pull request merged**
