### PR TITLE
Add Actix - rust web framework

### PR DESCRIPTION
**Pull request by fafhrd91**

### CODE REVIEW

**Comment by fafhrd91** [comment]
Btw when do you plan to updates stats?

**Comment by tbrand** [comment]
Sorry, currently  Im at vacation without any PC. I'll update after I return.

**Comment by fafhrd91** [comment]
sure, np

**Comment by tbrand** [comment]
Updated :tada:
https://github.com/tbrand/which_is_the_fastest/releases/tag/v1.2.3

**Pull request merged**
