### PR TITLE
[wip] Add laravel on php 7

### PR DESCRIPTION
**Pull request by waghanza**
Hi,

In would be interesting to add [Laravel](https://laravel.com) on `PHP` **7**.

Regards,

### CODE REVIEW

**Comment by tbrand** [comment]
Oops, it still work in progress, sorry for the early comment

**Comment by waghanza** [comment]
@tbrand Yes, its kind a too big (I'm new on PHP7)

**Comment by tbrand** [comment]
OK, keep it as it.

**Comment by waghanza** [comment]
close, since this `PR` will **completely** be re-written

**Pull request closed without merging**
