### PR TITLE
Upgrade actix to version 0.4

### PR DESCRIPTION
**Pull request by fafhrd91**

### CODE REVIEW

**Comment by waghanza** [comment]
@fafhrd91 good catch, but could you remove version checking -> not revelant in our case
I don't know about `rust` but probably a _*_ will install the **latest** stable

**Comment by fafhrd91** [comment]
do you mean remove version from actix project?

**Comment by waghanza** [comment]
@fafhrd91 probably, I can fix it upgrading to latest stable. 

The **goal** of this project is only about comparison, but it could be accurate to compare last stable version, na ?

**Comment by fafhrd91** [comment]
But for sure, you want result be reproducible and in this case it is just easier to pin versions

**Comment by fafhrd91** [comment]
btw when do you guys plan to run bench again?

**Comment by waghanza** [comment]
@fafhrd91 not an idea :stuck_out_tongue_closed_eyes: in fact @tbrand display the result

=> `rust` is not **working** for me

**Comment by fafhrd91** [comment]
I don’t understand your comment

**Comment by waghanza** [comment]
@fafhrd91 I mean, we split work
---
@tbrand display the result and I help maintaining, so I can give you any date

@tbrand will answer :-)

**Comment by fafhrd91** [comment]
ok, thanks

**Pull request merged**
