### PR TITLE
Introducing Vibora

### PR DESCRIPTION
**Pull request by greed2411**
I can't give any assurances about the code. I just tested it but, the `SO_REUSEPORT` is causing trouble, but wanted contribute anyway. That's why I've mentioned Introducing not Adding.

Partially solves #282 

If you guys can solve it, please do let me know.

edit: idk how to add the target to readme file, because they have already been ranked, therefore didn't know where to put the name in readme.md. also benchmarker.cr is in `tools/src/benchmarker.cr` not in `benchmarker/benchmarker.cr` as mentioned in the readme. 

Peace.

### CODE REVIEW

**Comment by waghanza** [comment]
The `README` has to be completely rewritten ^^

**Comment by waghanza** [comment]
@greed2411 `SO_REUSEPORT` is already implement, https://github.com/vibora-io/vibora/blob/master/vibora/workers/handler.py#L26, no ?

**Comment by greed2411** [comment]
@waghanza ik that, but idk why but I can't import `SO_REUSEPORT` from socket. What I'm getting is `ImportErrror` because of that file.

Okay so, japronto is faster than vibora. And tornado is still sitting at the bottom. Sad.

**Comment by waghanza** [comment]
@greed2411 the results are no **ready** to be `used` (for me also its strange `django` is high ranked)

**Comment by waghanza** [comment]
@greed2411 

| Framework (Middleware)    |    Requests / s |         Latency |   99 percentile |      Throughput |
|---------------------------|----------------:|----------------:|----------------:|-----------:|
| sanic                     | 4291.33 | 294510.67 | 2624570.67 | 2.46 MB |
| japronto                  | 48795.00 | 20601.67 | 29932.33 | 19.66 MB |
| flask                     | 1136.33 | 85623.00 | 106144.00 | 0.82 MB |
| django                    | 10868.33 | 94937.67 | 249561.67 | 11.12 MB |
| tornado                   | 7598.33 | 126527.67 | 229543.00 | 5.36 MB |
| vibora                    | 20470.33 | 95694.67 | 285971.00 | 13.10 MB |

I've turned `django` into `async` with http://meinheld.org/

**Comment by greed2411** [comment]
Oh there's django2, which is async. I forgot that. Btw did you try meinheld and gunicorn over tornado with that modification? Ik bdarnell, didn't recommend it. But still curious how it would work with meinheld and `tornado.wsgi`, but don't push yourself over it.

**Comment by greed2411** [comment]
@waghanza thanks then, i guess, that's all we can do for `tornado`.

**Comment by waghanza** [comment]
@greed2411 We will be `unhappy`. `django` with http://meinheld.org/ is **fatser** than `tornado`

| Language (Runtime)        | Framework (Middleware)    |    Requests / s |         Latency |   99 percentile |      Throughput |
|---------------------------|---------------------------|----------------:|----------------:|----------------:|-----------:|
| python                    | sanic                     | 13839.00 | 72102.33 | 182695.33 | 7.70 MB |
| python                    | japronto                  | 79228.33 | 12562.33 | 18041.67 | 31.49 MB |
| python                    | flask                     | 17655.67 | 60496.33 | 174634.00 | 15.30 MB |
| python                    | django                    | 9363.33 | 109721.33 | 342149.67 | 8.56 MB |
| python                    | tornado                   | 6060.67 | 165611.67 | 794569.67 | 4.41 MB |
| python                    | vibora                    | 27051.33 | 55770.00 | 117515.33 | 18.33 MB |

**Pull request merged**
