### PR TITLE
update mofuw

### PR DESCRIPTION
**Pull request by 2vg**
Fix code for newly designed mofuw.

### CODE REVIEW

**Comment by waghanza** [comment]
Thanks

`nim` is failing https://travis-ci.com/tbrand/which_is_the_fastest/jobs/134796334

BTS, it seems to be on `jester` side

**Comment by dom96** [comment]
Jester 0.3.0 requires Nim ``devel``. So you need to update Nim.

**Comment by dom96** [comment]
I updated this recently, you might want to grab it: https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Nim/jester

**Comment by dom96** [comment]
Also, it'd be cool if you include httpbeast in this too :)

https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Nim/httpbeast

**Comment by waghanza** [comment]
@dom96 would you mind create an issue for `httpbeast` integration ?

I'll manually update jester impl

**Comment by waghanza** [comment]
@dom96 do you know when next `nim` while be release ?

**Comment by dom96** [comment]
@waghanza Not certain. But hopefully sometime in August. You can grab a ``devel`` version of Nim easily using ``choosenim``, check out my dockerfile for how to do it: you can pin it to a specific commit easily.

**Comment by waghanza** [comment]
@2vg `mofuw ` is failing https://travis-ci.com/tbrand/which_is_the_fastest/jobs/135313930

**Pull request merged**
