### PR TITLE
Adding the Elixir framework Plug to benchmarks

### PR DESCRIPTION
**Pull request by kelvinst**

### CODE REVIEW

**Comment by tbrand** [comment]
Thanks!! I will re-measure this!!

**Comment by kelvinst** [comment]
THANK YOU!

**Comment by kelvinst** [comment]
Any prediction when you will re-measure and merge the new results?

**Comment by tbrand** [comment]
ASAP.
Sadly I have no time today, so it might be tomorrow.

**Comment by tbrand** [comment]
This commit has been included in first release:tada:
Thanks for your commit again and waiting for your new PR. :smile:
https://github.com/tbrand/which_is_the_fastest/releases/tag/v1.0.0

**Pull request merged**
