### PR TITLE
Don't needlessly allocate in Rocket code

### PR DESCRIPTION
**Pull request by SergioBenitez**

### CODE REVIEW

**Comment by SergioBenitez** [comment]
Just wanted to show the potential change here. Feel free to implement it if you'd like. :)

**Comment by kiliankoe** [comment]
Makes sense! 🙈

Any possible improvements should definitely be added, I'm all for adding this change.

**Comment by tbrand** [comment]
> Any possible improvements should definitely be added

Absolutely💯
Thanks @SergioBenitez !!!

**Comment by SergioBenitez** [comment]
Have the benchmarks been rerun with this? I've run the benchmarks locally, and I see timing on the order of Iron/Nickel, not the 2.5x worse value I see now.

**Comment by kiliankoe** [comment]
[Others](https://github.com/tbrand/which_is_the_fastest/pull/32#issuecomment-300272507) have noticed a certain discrepancy regarding rocket's stats as well, but I don't think anybody knows why it differs. On my machine it's definitely comparable to iron and nickel as well.

**Pull request closed without merging**
