### PR TITLE
add fastify as a target

### PR DESCRIPTION
**Pull request by thekemkid**

### CODE REVIEW

**Comment by tbrand** [comment]
Will check this! thanks!

**Comment by tbrand** [comment]
Failed to pass the benchmark since the response contains double quotes.
May be this issue https://github.com/fastify/fastify/issues/207 related to the problem.
Could you fix?

Thanks!

**Comment by thekemkid** [comment]
Nice Catch! Updated 👍

**Comment by tbrand** [comment]
Hmm... it's still failed for the POST request with empty body...
https://github.com/fastify/fastify/issues/297

**Comment by tbrand** [comment]
Will close this since fastify is cannot be added under the rules.
If you can fix it, please re-post new PR.
Thanks!

**Pull request closed without merging**
