### PR TITLE
Iron dockerfile

### PR DESCRIPTION
**Pull request by Guillaume-Mayer**
Sorry I'm new to PR.
I did this one on a dedicated branch, with the docker-compose.yml update

### CODE REVIEW

**Comment by tbrand** [comment]
Got it! Will check this!

**Comment by Guillaume-Mayer** [comment]
I used multi-stage build, so it requires Docker 17.05+

**Comment by tbrand** [comment]
I got a following error
```
Step 3/7 : RUN cargo build --release
 ---> Running in 720eca92bf4c
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to open: /home/rust/src/target/release/.cargo-lock

Caused by:
  Permission denied (os error 13)
ERROR: Service 'iron' failed to build: The command '/bin/sh -c cargo build --release' returned a non-zero code: 101
```

Could you solve this?
```
```

**Comment by Guillaume-Mayer** [comment]
It should work now

**Comment by tbrand** [comment]
Thanks!!

**Pull request merged**
