### PR TITLE
Use Puma

### PR DESCRIPTION
**Pull request by georgeu2000**

### CODE REVIEW

**Comment by waghanza** [comment]
@georgeu2000 :+1: using the default **webrick** instead of **puma** will break benchmark suite for ruby ;-)

after each launch, the **puma** process is killed by the benchmarking tool

+ would you mind remove the ruby version in  `Gemfile` (break portability) ?

@tbrand If you need I can propose myself to **review** / **merge** `PR` :stuck_out_tongue_winking_eye:  (especially for `ruby` / `crystal` )

**Comment by whatisok6** [comment]
@waghanza That's the reason why I added you to this repository as a collaborator. 👍

**Comment by tbrand** [comment]
@waghanza That's the reason why I added you into this repository as a collaborator. :+1:

**Comment by waghanza** [comment]
@tbrand I still see the `Contributor` flag on my message

**Comment by georgeu2000** [comment]
@waghanza 
> using the default webrick instead of puma will break benchmark suite for ruby ;-)
It sure did.

> would you mind remove the ruby version in Gemfile (break portability) ?
Done.

**Comment by tbrand** [comment]
@waghanza I already sent an invite email to you. ✉️

**Comment by waghanza** [comment]
@tbrand sure ... now I have seen.  The email was drow on my messy inbox :wink:

**Pull request merged**
