### PR TITLE
Add server Swift basic "HTTP" module

### PR DESCRIPTION
**Pull request by seabaylea**
Add the Swift Server API projects "HTTP" server to the benchmarks. This is a [Swift.org community project](https://swift.org/server-apis/) to provide a low level HTTP server that frameworks can build on top of.

GitHub project: https://github.com/swift-server/http

### CODE REVIEW

**Comment by tbrand** [comment]
Sorry, actually, the PR is not acceptable since the middleware doesn't parse path parameters but parsing in application layer.(here: https://github.com/tbrand/which_is_the_fastest/pull/75/files#diff-c4e56ea9f97b2b42bd7ee0394d2e275eR20)

If there is another way to parse them, patches are very welcome!
Thanks

**Comment by seabaylea** [comment]
Hi @tbrand. Sorry, I'd assumed from the "We want to know the response time, not a usability. So full-stack framework is at a disadvantage." statement that bare-bones HTTP servers were ok.

In order to provide this as a benchmark that people working on the HTTP project can run to test for performance, would you be ok me me forking it to here: https://github.com/swift-server/ (for that purpose only, and referring back to this project)?

**Comment by tbrand** [comment]
Of course!:heart:

**Comment by seabaylea** [comment]
Thanks @tbrand. I've placed the fork here:
https://github.com/swift-server/which_is_the_fastest

which links back to this upstream repo in the README.md.

**Pull request closed without merging**
