### PR TITLE
Dockerify2

### PR DESCRIPTION
**Pull request by tbrand**
I've fix the #180.
Now it's perfectly working with `bin/benchmarker -r 1`

```
> ./bin/benchmarker -r 1
Last update: 2018-04-17
```
OS: Darwin (version: 17.3.0, arch: x86_64)
CPU Cores: 8
threads: 9, requests: 1
```
Benchmark running ...
Done. <- rails
Done. <- sinatra
Done. <- roda
Done. <- rack-routing
Done. <- kemal
Done. <- router.cr
Done. <- raze
Done. <- lucky
Done. <- amber
Done. <- spider-gazelle
Done. <- echo
Done. <- gorilla_mux
Done. <- iris
Done. <- fasthttprouter
Done. <- gin
Done. <- actix
Done. <- iron
Done. <- nickel
Done. <- rocket
Done. <- express
Done. <- polka
Done. <- plug
Done. <- phoenix
Done. <- vapor
Done. <- perfect
Done. <- kitura
Done. <- akkahttp
Done. <- aspnetcore
Done. <- sanic
Done. <- japronto
Done. <- flask
Done. <- django
Done. <- tornado
Done. <- jester
Done. <- mofuw
```

### CODE REVIEW

**Comment by tbrand** [comment]
@waghanza I've pushed my patches at here.
If you are ok, please merge this.
If you have more patches, please push directly on this and request review for me.

Thanks!

**Comment by tbrand** [comment]
**I really totally don't understand why you say I lied.** Please stop saying like that strong words.
I just try to confirm that the all containers working well or not here.
That is the reason why I put the `-r 1` option for the execution.

**Comment by OvermindDL1** [comment]
No no!  I'm not saying you lied at all!  I'm stating that the display from the output is lying about what it is actually doing (it implies it is using 9 threads worth of power to siege the servers, which it is not doing), plus I don't think that was your code anyway.  ^.^

**Comment by tbrand** [comment]
Oh OK, sorry for that. Let me discuss about it at another place. 😄

**Comment by tbrand** [comment]
@waghanza Of course. Please open the channel and put the link onto README.md :+1:
BTW, is this PR OK for @waghanza ?
Your commits in this.

**Comment by waghanza** [comment]
@OvermindDL done it :+1:

I'll PR about this next week

**Comment by tbrand** [comment]
@waghanza What's going on?

**Comment by waghanza** [comment]
I'll merge this after test (somewhere around tomorrow)

**Comment by AlexWayfer** [comment]
> * use shards to release all binaries (client,benchmarker)

Sorry, what? Do you know that neither `make` nor `neph` doesn't build `bin/benchmarker` now, what is written in `README` about usage.

**Comment by waghanza** [comment]
@AlexWayfer yeah the `README` is quiet  `outdated `

After `publishing` **results**, I will re-write the documentation

**Comment by AlexWayfer** [comment]
> After publishing results, I will re-write the documentation

OK, thank you!

**Pull request merged**
