### PR TITLE
Add ASP.NET Core framework

### PR DESCRIPTION
**Pull request by petersonfs**
Hello! ASP.NET Core is the newest web framework by Microsoft. I would like to include in benchmarks, everyone will be suprised with the results.

Any help you need, just tell me.

### CODE REVIEW

**Comment by tbrand** [comment]
Awesome!!

This is just a memo.
https://www.microsoft.com/net/core#macos

**Comment by petersonfs** [comment]
First results from my computer:

```bash
> bin/benchmarker csharp crystal

Language (Runtime)        Framework (Middleware)          Max [sec]       Min [sec]       Ave [sec]
------------------------- ------------------------- --------------- --------------- ---------------
crystal                   kemal                            7.176058        6.552719        6.763581
crystal                   router_cr                        7.466896        6.333731        6.961336
csharp                    aspnetcore                       7.098271        6.363752        6.562894

 -- Ranking (Language) -- 
1. csharp (aspnetcore) 6.562894
2. crystal (kemal) 6.7635806

 -- Ranking (Framework) -- 
1. aspnetcore 6.562894
2. kemal 6.7635806
3. router_cr 6.9613358
```

**Comment by tbrand** [comment]
Hmm...? It's very strange why kemal is faster then router.cr?

**Comment by petersonfs** [comment]
I don't know @tbrand, i just ran the benchmarker.

My machine:

```bash
MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports)
2,9 GHz Intel Core i5
16 GB 2133 MHz LPDDR3
```

**Comment by OvermindDL1** [comment]
I ran `make csharp` or `make aspnetcore` and I'm getting that it is outputting:
```shell
  aspnetcore -> /home/me/tmp/which_is_the_fastest/csharp/aspnetcore/bin/Debug/netcoreapp1.1/aspnetcore.dll
```
Then it tries to run:
```shell
ln -s -f ../csharp/aspnetcore/bin/server_csharp_aspnetcore bin/.
```
However the file `csharp/aspnetcore/bin/server_csharp_aspnetcore` does not exist, so it is an empty link.  It seems to be building a dll, not an executable.

/me is on Ubuntu

**Comment by tbrand** [comment]
I' tried and same to @OvermindDL1.
Could you fix it and merge the latest to fix conflics?

**Comment by tbrand** [comment]
Thanks for this! I've fixed this and merged in another PR!:tada:

**Pull request merged**
