### PR TITLE
Add Polka (Node.js)

### PR DESCRIPTION
**Pull request by lukeed**
Adds a normal Polka app as well as Polka running within a cluster.

Also modified `.gitignore` to hide all `node_modules` by default~

FWIW, I didn't shut down everything for a clean environment, but my results nonetheless:

```
OS: Darwin (version: 17.4.0, arch: x86_64)
CPU Cores: 8
---

| Language (Runtime)        | Framework (Middleware)    |       Max [sec] |       Min [sec] |       Ave [sec] |
|---------------------------|---------------------------|-----------------|-----------------|-----------------|
| node                      | express                   |       14.045810 |       13.786849 |       13.860336 |
| node                      | clusterexpress            |        6.542760 |        6.045073 |        6.294131 |
| node                      | polka                     |        7.428920 |        7.351898 |        7.406287 |
| node                      | clusterpolka              |        3.814742 |        3.681836 |        3.740319 |
```

---

_Closes #104_

### CODE REVIEW

**Comment by tbrand** [comment]
Awesome!:tada:

**Comment by kalicki** [comment]
@tbrand update result in readme?!

**Comment by tbrand** [comment]
Sorry, see https://github.com/tbrand/which_is_the_fastest/pull/102

**Comment by tbrand** [comment]
Updated :tada:
https://github.com/tbrand/which_is_the_fastest/releases/tag/v1.2.3

**Pull request merged**
