### PR TITLE
Added Raze and Iris to the benchmarks! (Crystal & Go)

### PR DESCRIPTION
**Pull request by krypton97**
Raze claims to be faster than Kemal. Also Iris claims to be the fastest Go framework.

### CODE REVIEW

**Comment by tbrand** [comment]
Sorry for late reply:cry:
I'll check this soon!

**Comment by krypton97** [comment]
@tbrand ok, no worries ;)

**Comment by tbrand** [comment]
The conflict will be fixed by myself, don't worry.:smile:

**Comment by krypton97** [comment]
@tbrand I would've fix it, but I'm not allowed o.O. Also I should've added amber as well

**Comment by tbrand** [comment]
Im working for new result.
These comits are in it😀

**Comment by krypton97** [comment]
@tbrand There's an issue with the kemal configs, the static handler is not disabled..

	Kemal.config do |cfg|
	  cfg.serve_static = false
	  cfg.logging = false
	end

Also I've got amber as well too here if it's ok to add it https://github.com/krypton97/http-benchmarks/tree/master/crystal

**Comment by tbrand** [comment]
Of course very welcome, but please wait for tomorrow's update😅

**Comment by krypton97** [comment]
Ok, no problem. Seems like go and crystal are the main players here ;)

**Comment by tbrand** [comment]
Thanks for your contribution!:tada:
https://github.com/tbrand/which_is_the_fastest/releases/tag/v1.2.0

I will close the PR since these commits are in it, thanks again!

**Pull request closed without merging**
