### PR TITLE
update nim/mofuw

### PR DESCRIPTION
**Pull request by 2vg**
Use an efficient routing module.

### CODE REVIEW

**Comment by waghanza** [comment]
@2vg still failing
I have `Error: unhandled exception: No such file or directory [OSError]` when launching **binary**

**Comment by 2vg** [comment]
It seems there was a problem with mofuw.
Please make a build request again and start CI.

**Comment by waghanza** [comment]
I have restart the build ;-)

but I'm also testing on my `workstation`

**Comment by 2vg** [comment]
build is success.
sorry mofuw's problem x(

**Pull request merged**
