### PR TITLE
[DNM] Add Fastify (node)

### PR DESCRIPTION
**Pull request by thiamsantos**

### CODE REVIEW

**Comment by thiamsantos** [comment]
Conflicts resolved.

**Comment by kalicki** [comment]
Brazuca! Mandou bem =)

**Comment by waghanza** [comment]
Awesome, I have just a question @thiamsantos. 

I use to come from Ruby world and I use to have the equivalent of **~** in `package.json` instead of **^**.

Is it node recommanded to use **~** since it keeps minor version (keep stability)

**Comment by thiamsantos** [comment]
> Is it node recommanded to use ~ since it keeps minor version (keep stability)

Yeah, you are completely. Generally we don't worry about that because the lockfiles ensure this stability. But maybe a should update to use a tilde range.

**Pull request merged**
